# Generated by Django 5.2 on 2025-05-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
    ]
