# Generated by Django 5.2 on 2025-05-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20250525_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifaenergia',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de la tarifa', null=True),
        ),
        migrations.AddField(
            model_name='tarifaenergia',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, help_text='Fecha de finalización de la tarifa', null=True),
        ),
        migrations.AddField(
            model_name='tarifaenergia',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha de inicio de la tarifa', null=True),
        ),
        migrations.AlterField(
            model_name='tarifaenergia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
