# Generated by Django 5.2 on 2025-05-25 18:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_tarifaenergia_descripcion_tarifaenergia_fecha_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCarga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('energia_consumida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
    ]
