# Generated by Django 5.2 on 2025-05-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_sesioncarga'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SesionCarga',
        ),
    ]
