# Generated by Django 5.2 on 2025-06-24 17:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_kwh_base', models.DecimalField(decimal_places=3, default=Decimal('0.300'), help_text='Precio base por kWh en euros', max_digits=5)),
                ('descuento_premium', models.DecimalField(decimal_places=3, default=Decimal('0.050'), help_text='Descuento para usuarios Premium en euros', max_digits=5)),
                ('email_contacto', models.EmailField(default='julio@juliomalaga.me', max_length=254)),
                ('nombre_creador', models.CharField(default='Julio Schneider', max_length=100)),
                ('app_nombre', models.CharField(default='EvEMaps', max_length=50)),
                ('disponibilidad_24_7', models.BooleanField(default=True)),
                ('promocion_activa', models.TextField(blank=True, help_text='Texto de promoción actual (opcional)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Chatbot',
                'verbose_name_plural': 'Configuración del Chatbot',
            },
        ),
    ]
