# Generated by Django 5.2.1 on 2025-05-13 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrolineras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conector',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=100)),
                ('potencia_kw', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoRecarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('potencia_kw', models.FloatField(blank=True, null=True)),
                ('tipo_conector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electrolineras.conector')),
            ],
        ),
        migrations.DeleteModel(
            name='Electrolinera',
        ),
    ]
