# Generated by Django 5.2 on 2025-05-23 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrolineras', '0003_reserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='puntorecarga',
            name='energia_actual_sesion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='puntorecarga',
            name='energia_suministrada_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='puntorecarga',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('reservado', 'Reservado'), ('offline', 'Fuera de Servicio')], default='disponible', max_length=15),
        ),
        migrations.CreateModel(
            name='SesionCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('porcentaje_bateria_inicial', models.IntegerField(default=20)),
                ('porcentaje_bateria_actual', models.IntegerField(default=20)),
                ('energia_consumida', models.FloatField(default=0)),
                ('punto_recarga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrolineras.puntorecarga')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='electrolineras.reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
