"""
Django settings for electrolineras_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%nyt9ci_gm3$*o^qe+53i*56vf2c8s!ypnq7$f+g$=^ejx@%lr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '10.0.2.2',
    'evemaps.juliomalaga.me',
    'evemaps.pythonanywhere.com'
]



# Application definition

INSTALLED_APPS = [
    'registration',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'electrolineras',
    'profiles',
    'core',
    'messenger',
    'payments',  # Nueva aplicación de pagos
    'rest_framework',
    'pages.apps.PagesConfig',
    'tinymce',  # Add TinyMCE to installed apps
    'corsheaders',
]

MIDDLEWARE = [
    'core.middleware.BlockDirectLoginAccessMiddleware',  # Añade aquí tu middleware personalizado
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'electrolineras_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'electrolineras_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG = {
    'height': 300,
    'width': 'auto',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 10,
    'selector': 'textarea',
    'theme': 'silver',
    'plugins': '''
        textcolor save link image media preview codesample contextmenu
        table code lists fullscreen insertdatetime nonbreaking
        contextmenu directionality searchreplace wordcount visualblocks
        visualchars code fullscreen autolink lists charmap print hr
        anchor pagebreak
        ''',
    'toolbar1': '''
        fullscreen preview bold italic underline | fontselect,
        fontsizeselect | forecolor backcolor | alignleft alignright |
        aligncenter alignjustify | indent outdent | bullist numlist table |
        | link image media | codesample |
        ''',
    'toolbar2': '''
        visualblocks visualchars |
        charmap hr pagebreak nonbreaking anchor | code |
        ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
}

# Auth redirects
LOGIN_REDIRECT_URL = 'home'  # Redirigir a la página de inicio después del login en lugar de al perfil
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = '/accounts/login/'  # URL de login para redirigir a los usuarios no autenticados

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jjse79@gmail.com'  # Reemplaza con tu correo de Gmail
EMAIL_HOST_PASSWORD = 'foqhqssweyhnlxky'  # Reemplaza con tu contraseña de aplicación
DEFAULT_FROM_EMAIL = 'jjse79@gmail.com'  # Correo para envíos

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Configuración de Stripe
# IMPORTANTE: En producción, estas claves deben estar en variables de entorno
# Las claves mostradas aquí son de PRUEBA y deben ser reemplazadas

# Claves de prueba de Stripe (reemplazar con las reales)
STRIPE_PUBLISHABLE_KEY = 'pk_test_51RSBOfQFcvigGkXXijjkijmBd62X9byrfX8BA9NLUARc60ZwoaqvrNx9DkcwEZqahbjnIFhn2H5eDUSKYIzf7fMH00K6OcsDPl'  # Clave pública de prueba
STRIPE_SECRET_KEY = 'sk_test_51RSBOfQFcvigGkXXhDJXIRboYegLXYXKqEY06QB40Mhah3qL87aG8CDpx9vFM4egiJ4M2Wt9LNCM4a018yQEdFHr00nYJvh5A7'       # Clave secreta de prueba
STRIPE_WEBHOOK_SECRET = 'work-wows-warmer-hail'  # Secreto del webhook actualizado

# Configuración del sistema de pagos
PAYMENT_PER_KWH = 0.30  # Precio por kWh en euros (fácilmente ajustable)
PAYMENT_CURRENCY = 'eur'  # Moneda para los pagos
PAYMENT_SUCCESS_URL = 'http://localhost:8000/payments/success/'  # URL de éxito
PAYMENT_CANCEL_URL = 'http://localhost:8000/payments/cancel/'    # URL de cancelación

# Configuración para manejar cookies seguras y encabezados de proxy
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')